#!/usr/bin/env bash
#
# Writes frontend/.env.local from a root configuration's Terraform outputs.
#
# Vite loads .env.local for `npm run dev` and `npm run build` alike, so this is the
# single source of configuration for local development and for deployment. The file is
# gitignored and must stay that way.
#
# TF_DIR is the root configuration that called the module. It defaults to the complete
# example; point it at your own:
#
#   TF_DIR=../my-infra ./scripts/frontend-env.sh
#
# Your root configuration must re-export the six outputs read below. Both bundled
# examples do; if yours does not, this fails naming the missing output.

set -euo pipefail

MODULE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="${TF_DIR:-examples/complete}"

# Resolved so a relative TF_DIR is interpreted against the module root rather than
# against whatever directory the caller happened to be in.
case "${TF_DIR}" in
  /*) TF_ABS="${TF_DIR}" ;;
  *)  TF_ABS="${MODULE_ROOT}/${TF_DIR}" ;;
esac

APP_DIR="${MODULE_ROOT}/frontend"
ENV_FILE="${APP_DIR}/.env.local"

command -v terraform >/dev/null || { echo "error: terraform not found on PATH" >&2; exit 1; }
[ -d "${TF_ABS}" ] || { echo "error: TF_DIR '${TF_DIR}' is not a directory" >&2; exit 1; }
[ -d "${APP_DIR}" ] || { echo "error: no frontend at ${APP_DIR}" >&2; exit 1; }

# Every value is read and checked before the file is written. Values are assigned to
# variables rather than substituted straight into a heredoc, because a failing $( )
# inside a heredoc does not fail the enclosing redirect — it silently yields an empty
# string, which produces a frontend that loads and then cannot sign in.
read_output() {
  local name="$1" value
  if ! value="$(terraform -chdir="${TF_ABS}" output -raw "$name" 2>/dev/null)"; then
    echo "error: could not read Terraform output '${name}' from ${TF_DIR}." >&2
    echo "       Not initialised?  terraform -chdir=${TF_DIR} init" >&2
    echo "       Not applied?      terraform -chdir=${TF_DIR} apply" >&2
    echo "       Output missing?   your root configuration must re-export it." >&2
    return 1
  fi
  if [ -z "${value}" ]; then
    echo "error: Terraform output '${name}' is empty." >&2
    return 1
  fi
  printf '%s' "${value}"
}

# List-typed outputs cannot use `output -raw`. Emitted comma-separated, which is what
# the frontend's config.ts splits on.
read_output_list() {
  local name="$1" value
  command -v jq >/dev/null || { echo "error: jq not found on PATH" >&2; return 1; }
  if ! value="$(terraform -chdir="${TF_ABS}" output -json "$name" 2>/dev/null | jq -r 'join(",")')" \
     || [ -z "${value}" ]; then
    echo "error: could not read list output '${name}' from ${TF_DIR}." >&2
    return 1
  fi
  printf '%s' "${value}"
}

# Accumulated then written in one go, so a missing output leaves the previous
# .env.local intact rather than truncating it.
BODY=""
emit() { BODY="${BODY}$1=$2"$'\n'; }

# Exactly the set frontend/src/config.ts reads, and no more. There is deliberately no
# bucket name or prefix: the browser reaches S3 only through the proxy. If you add a
# variable here, add it to config.ts and to the Amplify environment_variables in
# hosting.tf as well, or a locally served build and a deployed one will disagree.
emit VITE_USER_POOL_ID        "$(read_output user_pool_id)"
emit VITE_USER_POOL_CLIENT_ID "$(read_output user_pool_client_id)"
emit VITE_IDENTITY_POOL_ID    "$(read_output identity_pool_id)"
emit VITE_PROXY_FUNCTION_NAME "$(read_output proxy_function_name)"
emit VITE_MODEL_IDS           "$(read_output_list model_ids)"

# Read from Terraform rather than from AWS_REGION, so the browser cannot be built for a
# different region than the backend was applied in.
emit VITE_AWS_REGION          "$(read_output region)"

{
  echo "# Generated by scripts/frontend-env.sh from ${TF_DIR} Terraform outputs."
  echo "# Do not edit by hand and do not commit. Regenerate with:"
  echo "#   make frontend-env TF_DIR=${TF_DIR}"
  printf '%s' "${BODY}"
} > "${ENV_FILE}"

echo "wrote ${ENV_FILE}"
sed 's/^/  /' "${ENV_FILE}"
